name: Build Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install yarn
        run: npm install yarn -g
      - name: install vuepress
        run: yarn add global vuepress
      - name:
        run: npm run src:build
      - name: Commit Files
        run: |
          git config --local user.email "build@sunshower.io"
          git config --local user.name "josiahhaswell"
          cp CNAME docs/
          git add docs
          git commit -am "Releasing..."
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}




