name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Install Maven Dependencies
      run: mvn install -f bom
    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1
      env:
        JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
      with:
        gradle-version: 6.0.1
        arguments: assemble build sA -i
