name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install yarn
        run: npm install yarn -g
      - name: install vuepress
        run: yarn add global vuepress
      - name:
        run: npm run docs:build
